# https://medium.com/@faidfadjri/how-to-setup-laravel-nginx-using-docker-2023-ba9de4b60d04
# version: "3"

networks:
  lemp:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: ${SERVICE_RESTART}
    tty: true
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${SOURCE_FOLDER}:/var/www:delegated
    depends_on:
      - php
    networks:
      - lemp

  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
        - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
        # - INSTALL_PGSQL=${PHP_FPM_INSTALL_PGSQL}
        # - INSTALL_OCI8=${PHP_FPM_INSTALL_OCI8}
        # - INSTALL_PGSQL=${PHP_FPM_INSTALL_PGSQL}
        # - INSTALL_PG_CLIENT=${PHP_FPM_INSTALL_PG_CLIENT}
        # - INSTALL_POSTGIS=${PHP_FPM_INSTALL_POSTGIS}
        # - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
        # - INSTALL_MONGO=${PHP_FPM_INSTALL_MONGO}
    container_name: php
    restart: ${SERVICE_RESTART}
    tty: true
    expose:
      - "9000"
    volumes:
      - ${SOURCE_FOLDER}:/var/www:delegated
    networks:
      - lemp
  
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    restart: ${SERVICE_RESTART}
    volumes:
      - ${DATABASE_FOLDER}/mariadb:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - lemp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    # restart: always
    ports:
      - "${PMA_PORT}:80"
    volumes:
      - /sessions
    # links:
    #   - mariadb  
    networks:
      - lemp
      